# Generated by Django 5.2.3 on 2025-06-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('asset_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('market_hash_name', models.CharField(max_length=255)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('icon_url', models.URLField()),
                ('is_stattrak', models.BooleanField(default=False)),
                ('is_souvenir', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('steam_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.URLField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('steam_level', models.IntegerField(blank=True, null=True)),
                ('account_age_days', models.IntegerField(blank=True, null=True)),
                ('cs2_hours', models.FloatField(blank=True, null=True)),
                ('median_trade_time', models.IntegerField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('inspect_link', models.URLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.seller')),
            ],
        ),
    ]
