# Generated by Django 5.0.3 on 2025-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='account_age_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='account_age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
