# Generated by Django 5.0.3 on 2025-06-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_item_image_url_seller_account_age_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='account_age_months',
        ),
    ]
