# Generated by Django 5.0.3 on 2025-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_remove_seller_median_trade_time_seller_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='last_steam_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
