# Generated by Django 5.0.3 on 2025-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_rename_online_seller_is_online_listing_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='history_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
